name: "Cataclysm OSX Manual Build"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "build-data/osx/**"
      - "docs/**"
      - "doxygen_doc/**"
      - "gfx/**"
      - "lang/**"
      - "lgtm/**"
      - "tools/**"
      - "!tools/format/**"
      - "utilities/**"
      - "scripts/**"
      - "**.md"
      - "**.mdx"
# We only care about the latest revision of a PR, so cancel previous instances.
concurrency:
  group: osx-build-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_catatclysm:
    if: github.event.pull_request.draft == false

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: osx-tiles-arm
            os: macos-15
            tiles: 1
            artifact: osx-tiles-arm
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      ZSTD_CLEVEL: 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install runtime dependencies
        uses: BrettDong/setup-sdl2-frameworks@v1
        with:
          sdl2: 2.30.11
          sdl2-ttf: 2.24.0
          sdl2-image: 2.8.4
          sdl2-mixer: 2.8.0

      - name: Install build dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=yes HOMEBREW_NO_INSTALL_CLEANUP=yes brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gettext parallel llvm@20 astyle sqlite3 zlib
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip3 install mac_alias==2.2.0 dmgbuild==1.6.1 biplist polib luaparser

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.artifact }}-${{ github.ref_name }}
          restore-keys: |
            ${{ matrix.artifact }}-${{ github.ref_name }}
            ${{ matrix.artifact }}-main
            ${{ matrix.artifact }}-
          max-size: 500M
          verbose: 2
          save: ${{ github.event_name != 'pull_request' }}

      - name: Check Clang OK
        run: |
          echo "Clang++ version:"
          $(brew --prefix llvm@20)/bin/clang++ --version  # Ensure clang++ is installed and working

      - name: Build (Debug)
        shell: bash
        run: |
          source ./venv/bin/activate
          make -j3 CCACHE=1 TILES=1 SOUND=1 RELEASE=0 DEBUG_SYMBOLS=1 LOCALIZE=1 LANGUAGES=all \
            USE_HOME_DIR=1 OSX_MIN=11 PCH=0 FRAMEWORK=1 COMPILER=$(brew --prefix llvm@20)/bin/clang++ app

      - name: Create PR debug distribution zip
        shell: bash
        run: |
          artifact_suffix="pr-${{ github.event.pull_request.number }}-${GITHUB_SHA::7}"
          ditto -c -k --sequesterRsrc --keepParent Cataclysm.app "cbn-osx-tiles-debug-${artifact_suffix}.zip"

      - name: Upload PR debug distribution zip
        uses: actions/upload-artifact@v4.6.0
        with:
          name: cbn-osx-tiles-debug-pr-${{ github.event.pull_request.number }}
          path: cbn-osx-tiles-debug-*.zip
          if-no-files-found: error
          retention-days: 14
