name: "Cataclysm OSX Manual Build"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "build-data/osx/**"
      - "docs/**"
      - "doxygen_doc/**"
      - "gfx/**"
      - "lang/**"
      - "lgtm/**"
      - "tools/**"
      - "!tools/format/**"
      - "utilities/**"
      - "scripts/**"
      - "**.md"
      - "**.mdx"
# We only care about the latest revision of a PR, so cancel previous instances.
concurrency:
  group: osx-build-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

jobs:
  build_catatclysm:
    if: github.event.pull_request.draft == false

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: osx-curses-x64
            os: macos-15-intel
            tiles: 0
            artifact: osx-curses-x64
            ext: dmg
            content: application/x-apple-diskimage
          - name: osx-tiles-x64
            os: macos-15-intel
            tiles: 1
            artifact: osx-tiles-x64
            ext: dmg
            content: application/x-apple-diskimage
          - name: osx-curses-arm
            os: macos-15
            tiles: 0
            artifact: osx-curses-arm
            ext: dmg
            content: application/x-apple-diskimage
          - name: osx-tiles-arm
            os: macos-15
            tiles: 1
            artifact: osx-tiles-arm
            ext: dmg
            content: application/x-apple-diskimage
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      ZSTD_CLEVEL: 17

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install runtime dependencies
        uses: BrettDong/setup-sdl2-frameworks@v1
        with:
          sdl2: 2.30.11
          sdl2-ttf: 2.24.0
          sdl2-image: 2.8.4
          sdl2-mixer: 2.8.0

      - name: Install build dependencies
        run: |
          HOMEBREW_NO_AUTO_UPDATE=yes HOMEBREW_NO_INSTALL_CLEANUP=yes brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer gettext parallel llvm@20 astyle sqlite3 zlib cmake ninja
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip3 install mac_alias==2.2.0 dmgbuild==1.6.1 biplist polib luaparser

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.artifact }}-${{ github.ref_name }}
          restore-keys: |
            ${{ matrix.artifact }}-${{ github.ref_name }}
            ${{ matrix.artifact }}-main
            ${{ matrix.artifact }}-
          max-size: 500M
          verbose: 2
          save: ${{ github.event_name != 'pull_request' }}

      - name: Configure and Build with CMake
        run: |
          source ./venv/bin/activate
          export CC=$(brew --prefix llvm@20)/bin/clang
          export CXX=$(brew --prefix llvm@20)/bin/clang++
          cmake --preset ${{ matrix.tiles == 1 && 'osx-tiles' || 'osx-curses' }} -DRELEASE=ON
          cmake --build --preset ${{ matrix.tiles == 1 && 'osx-tiles' || 'osx-curses' }}

      - name: Create DMG
        run: |
          source ./venv/bin/activate
          cmake --build build --target osx-dmg
